### ISSUE TITLE
Is there recommendation for any test data?

### ISSUE THREAD

**Issue by dmsalsgh97** [cxzhu/Paired-Tag#1]
Hi, I'm trying to test paired-seq analysis pipeline.
I tried to use GEO data on GitHub hyperlinked, but it is in the private stage.

So, If you don't mind, can you recommend proper test data for Paired-seq analysis pipeline?
thanks

**Comment by cxzhu** [comment]
@dmsalsgh97 

If you are looking for data of [V1 dataset](https://www.nature.com/articles/s41594-019-0323-x), please refer to: [GSE130399](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE130399).

For the current version (which still under review), we have released the [GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE152020) now.

**Comment by dmsalsgh97** [comment]
Hi cxzhu,

Thanks for sharing your efforts!
I'll try it for understanding library structures of Paired-seq
