### ISSUE TITLE
Segmentation fault when converte rna bam to cell-counts matrice     

### ISSUE THREAD

**Issue by StrangerZN** [cxzhu/Paired-Tag#10]
Segmentation fault when run "reachtools bam2Mtx2 ${s}_sorted_rmdup.bam ${mm10_rna}". 
I added "chr" prefix to the "./refereces/mm10.RNA.txt" and used it as the annotation file  ${mm10_rna} here. mm10.fa downloaded from ucsc was used for earlier mapping.

**Comment by Xieeeee** [comment]
Hi,
I think this is probably the issue with the mm10.RNA.txt annotation. The file is actually a four-columns file separated by tab,  the last column is separated by space (e.g. ENSMUSG00000051951 Xkr4)

Would you mind telling us how you add the "chr" prefix? You can also try this and use the new annotation file. It should work:
`awk '{print "chr"$0}' ./refereces/mm10.RNA.txt > ./refereces/mm10.RNA.new.txt`

Best,
Yang

**Comment by StrangerZN** [comment]
Thanks! It works. I shouldn't replace the space in last column with tab.
