### ISSUE TITLE
ATAC data of Paired-seq looks strange using Signac

### ISSUE THREAD

**Issue by Telogen** [cxzhu/Paired-Tag#12]
Hi, Dr. Zhu, I'm processing ATAC data of Paired-seq using Signac
```
counts <- Read10X("./data/07.Paired-seq_DNA_filtered_matrix")
chrom_assay <- CreateChromatinAssay(counts,sep = c(":", "-"))
pbmc.ATAC <- CreateSeuratObject(chrom_assay,assay = "ATAC")
pbmc.ATAC <- RunTFIDF(pbmc.ATAC)
pbmc.ATAC <- FindTopFeatures(pbmc.ATAC, min.cutoff = 'q0')
pbmc.ATAC <- RunSVD(pbmc.ATAC)
DepthCor(pbmc.ATAC,n = 50)
pbmc.ATAC <- RunUMAP(pbmc.ATAC, dims = 2:50, reduction = 'lsi',verbose = F)

metadata <- read.csv('./data/01.Paired-Tag_seq_RNA_filtered_matrix/Nuclei_metaData.csv')
rownames(metadata) <- metadata$Cell_ID
metadata_ATAC <- metadata[colnames(pbmc.ATAC),]
pbmc.ATAC$true <- metadata_ATAC$Annotation

DimPlot(object = pbmc.ATAC, label = T,group.by = 'true') + NoLegend()
```
I got this UMAP as the output
![image](https://user-images.githubusercontent.com/54151359/171123569-68cb9b87-0c3f-4fef-b8d6-eb34e49f098f.png)
The UMAP looks strange, could you please give me some suggestions on how to deal with the data properly? Many thanks!

**Comment by cxzhu** [comment]
Hi @Telogen,

I can recover most of the major cell types consistent with RNA-based clustering with Signac by fine-tuning some parameters (please find the attached file).
[Untitled.html.zip](https://github.com/cxzhu/Paired-Tag/files/8807986/Untitled.html.zip)

By the way, I strongly recommend you to try [SnapATAC2](https://github.com/kaizhang/SnapATAC2) for processing of chromatin data, as in our hand the SnapATAC package showed a better cell type separation and speed in processing larger datasets.

Best,
Chenxu

**Comment by Telogen** [comment]
Thanks Dr. Zhu! I didn't expect TF-IDF method to have such a big impact on the results, and I'm very willing to have a try of SnapATAC2!
