### ISSUE TITLE
No input samples

### ISSUE THREAD

**Issue by wbszhu** [cxzhu/Paired-Tag#13]
Hi，
Thank you for such an excellent work~
I was looking for some suitable data for my recent work and happened to read your article. 
In general, we usually prepare input samples when preparing chip-seq experiments. Input sample are used to ignore regions with high levels of background binding during analysis, and to reduce the number of false positives during peak calling, differential binding. Therefore, input samples are generally prepared. I did not find input samples.([either Bulk_HeLa or Bulk_Brain](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE152020))
Maybe I missed some key sentences or words. Looking forward to your reply.
Thanks,
LuZhang

**Comment by cxzhu** [comment]
Hi @wbszhu,

Paired-Tag is based on CUT&Tag, and similar to all tagmentation-based methods, the background is extremely low and you can only get very limited reads from each single cell; thus input control is typically omitted in scCUT&Tag assays. 

You can read more information about controls in CUT&Tag experiments: https://www.nature.com/articles/s41596-020-0373-x.

**Comment by wbszhu** [comment]
Oh, thanks for your reply.
It's really embarrassing. I was in such a hurry that I missed the key information.
thanks a lot.
