### ISSUE TITLE
Empty files generated for RNA with bam2Mtx2

### ISSUE THREAD

**Issue by yoshihiko1218** [cxzhu/Paired-Tag#14]
Hi,

I am running the pipeline with data downloaded from GEO. The former steps run well, and I got sorted, duplication removed bam files. However, when I run the last step, "reachtools bam2Mtx2 ${s}_sorted_rmdup.bam ${mm10_rna}", it runs without any error. However, the generated files are all empty. 
Do you have any idea about what might lead to this problem?
The fa files was downloaded from https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/mm10.fa.gz
gtf file was downloaded from https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/genes/mm10.ensGene.gtf.gz
Then index was generated with code 
STAR --runMode genomeGenerate \
     --runThreadN 40 \
     --genomeDir ./mm10_STAR \
     --genomeFastaFiles mm10.fa \
     --sjdbGTFfile mm10.ensGene.gtf \
     --sjdbOverhang 75

**Comment by yoshihiko1218** [comment]
Also, I wonder how can barcodes.tsv, genes.tsv, and matrix.mtx generated by DNA sequencing be converted to a format that can be used in snapATAC?

**Comment by cxzhu** [comment]
Hi @yoshihiko1218,

As mentioned in the [readme file](https://github.com/cxzhu/Paired-Tag#2-mapping-to-the-genome), variables in the scripts will need to be modified according to your environment. Could you check [this shell script](https://github.com/cxzhu/Paired-Tag/blob/1c15c42c5716f2e90b1330d0930808583e1f3b76/shellscrips/03.proc_RNA.sh): have you changed all the variables as indicated in the file? Particularly, the "path-to-your-mm10-annotation-reference" to where you put your gene annotation reference file. The converted mm10 annotation file is available [here](https://github.com/cxzhu/Paired-Tag/blob/master/refereces/mm10.RNA.txt).

Once finished, the output will be a standard [Matrix Market format](https://math.nist.gov/MatrixMarket/formats.html). For how to load the datasets in a standard Matrix Market format to other packages, please contact the package developers.
