### ISSUE TITLE
rmdup for RNA?

### ISSUE THREAD

**Issue by Xieeeee** [cxzhu/Paired-Tag#15]
Currently both DNA and RNA are de-duplicated based on `cellid-umi-chr-start`. Considering the library construction process for RNA, shouldnt it be duplicated based merely on `cellid-umi` or `cellid-umi-chr`? Since tagmentation may generate different cutting end on the cDNA molecules originating from PCR duplicates. And now they are treated as different molecules.

**Comment by Xieeeee** [comment]
did a quick test on one RNA library, reads being removed as duplicates are actually significantly different (~20% reads), however this doesnt seem to have an effect on cell filtering and clustering that much. Besides median reads per cell post barcodes filtering is also similar.

**Comment by cxzhu** [comment]
I previously compared to collapse RNA reads within +/- 200 bp and seems do not seem to have many differences and thus in the current form kept the same dedup module for both DNA and RNA.

However, this may have varying effects on libraries of different saturation levels. This repo is to ensure the reproducibility of the published results. This enhancement, as well as other enhancement (i.e., allowing mismatches in UMI) will be included in future versions.
