### ISSUE TITLE
GEO data 

### ISSUE THREAD

**Issue by ManuSetty** [cxzhu/Paired-Tag#2]
Thanks for this great resource! 

I have a question about the GEO submission metadata. Some of the samples are associated with multiple antibodies in the annotation - could you please provide information on how to map the reads onto the specific antibody? 

An example screenshot:
![image](https://user-images.githubusercontent.com/2151404/118706692-86581e80-b7ce-11eb-9b92-3fbc54764ebe.png)

How do I figure out the antibody source of each read in these samples ?

**Comment by cxzhu** [comment]
Hi @ManuSetty,
Thank you for your interest in our data!
You can find the sample barcode annotation (tissue region, antibodies, rep#) in Extended Dat Fig. 2a, and the "Nuclei_metaData.xls" file associated with the RNA count matrix file in GEO.

**Comment by ManuSetty** [comment]
Thanks for the quick clarification @cxzhu !

**Comment by ManuSetty** [comment]
Another quick question: Can you please provide the prefix and sample correspondence used to generate the `Cell_ID` in the "Nuclei_metaData.xls". Thanks!

**Comment by cxzhu** [comment]
Hi @ManuSetty,

Here is the prefix list:
Sub_Lib# | Prefix
-- | --
H3K4me1_H3K27ac_#01 | 01
H3K4me1_H3K27ac_#02 | 02
H3K4me1_H3K27ac_#03 | 03
H3K4me1_H3K27ac_#04 | 04
H3K4me1_H3K27ac_#05 | 05
H3K4me1_H3K27ac_#06 | 06
H3K4me1_H3K27ac_#07 | 07
H3K4me1_H3K27ac_#08 | 08
H3K4me1_H3K27ac_#09 | 09
H3K4me1_H3K27ac_#10 | 10
H3K4me1_H3K27ac_#11 | 11
H3K4me1_H3K27ac_#12 | 12
H3K4me1_H3K27ac_#13 | 13
H3K4me1_H3K27ac_#14 | 14
H3K4me1_H3K27ac_#15 | 15
H3K4me1_H3K27ac_#16 | 16
H3K27me3_H3K9me3_#01 | 21
H3K27me3_H3K9me3_#02 | 22
H3K27me3_H3K9me3_#03 | 23
H3K27me3_H3K9me3_#04 | 24
H3K27me3_H3K9me3_#05 | 25
H3K27me3_H3K9me3_#06 | 26
H3K27me3_H3K9me3_#07 | 27
H3K27me3_H3K9me3_#08 | 28
H3K27me3_H3K9me3_#09 | 29
H3K27me3_H3K9me3_#10 | 30
H3K27me3_H3K9me3_#11 | 31
H3K27me3_H3K9me3_#12 | 32
H3K4me3_#01 | 41
H3K4me3_#02 | 42
H3K4me3_#03 | 43
H3K4me3_#04 | 44
H3K4me3_#05 | 45
H3K4me3_#06 | 46
H3K4me3_#07 | 47
H3K4me3_#08 | 48
Paired-seq_#01 | 51
Paired-seq_#02 | 52
Paired-seq_#03 | 53
Paired-seq_#04 | 54
Paired-seq_#05 | 55
Paired-seq_#06 | 56

**Comment by ManuSetty** [comment]
Perfect - thanks @cxzhu !
