### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by yang2sc** [cxzhu/Paired-Tag#23]
Dear Dr. Zhu,
 
We are interested in using a modified version of some of the code that you developed in Paired-tag in the analysis of our own dataset and would like to be able to distribute this code as a part of our analysis pipeline to make it easier for others to use our method. Would you be willing to licence your code in a way that permits this? I see that this repository currently lacks a license meaning that by default you reserve all rights to the content and technically others cannot distribute it or derivatives of it without your permission. However, I see that you have made your code publicly available and that you used the CC-BY licence for the lab protocol for this method on protocol exchange, so perhaps this was not your intent? If you would like to do this, could you please add a `LICENCE` file to your project with a license of your choice? 
 
Many thanks,
Yang

**Comment by cxzhu** [comment]
Dear Yang,

Updated. Thanks.

**Comment by yang2sc** [comment]
That's great, thanks a lot! 👍
