### ISSUE TITLE
bam to mtx issue

### ISSUE THREAD

**Issue by xindongnov** [cxzhu/Paired-Tag#4]
Hi Chenxu,

Thanks for this wonderful resource! I am using `reachtools bam2Mtx2` to convert dedup bam to matrix files. But it broke when writing content to genes.tsv . Is there any solution to this issue? Did I forget to install anything? Thanks!

commands:
```
reachtools bam2Mtx2 GSM4874904_mm10_sorted_rmdup.bam ref.txt
```

logs :
```
Reading ref annotation...
Processing sam/bam file...
Passing cell post filter to new hash...
Cleaning memory...
Outputing MatrixFactory Format File...
Segmentation fault (core dumped)
```

top lines of ref.txt (macs2 peak of merged fastq files) :
```
chr1	3094714	3095663	chr1_3094714_3095663	chr1_3094714_3095663
chr1	3119625	3120898	chr1_3119625_3120898	chr1_3119625_3120898
chr1	3201325	3201703	chr1_3201325_3201703	chr1_3201325_3201703
chr1	3212568	3213436	chr1_3212568_3213436	chr1_3212568_3213436
...
...

```

Btw, if I use `perlscripts/merge_mtx.pl` to merge sub-library files into one in the following step with GEO data as your mentioned in issue#2, are the cell barcodes consistent with your paper? Now the reads names look like `GSM4874904_temp1.17948477:64:86:01:ATTCCTCTTG` in the bam file. Thanks!

Best,
Xin

**Comment by xindongnov** [comment]
Hi,

After I checked the code, I just found that the delimiter between the fourth and fifth columns is space instead of tab in the ref files! It works fine now! 

Thanks again for this useful resource and tool!

Best,
Xin

**Comment by cxzhu** [comment]
Hi @xindong95 

I am glad you solved the ref file format problem.

> 
> Btw, if I use `perlscripts/merge_mtx.pl` to merge sub-library files into one in the following step with GEO data as your mentioned in issue#2, are the cell barcodes consistent with your paper? Now the reads names look like `GSM4874904_temp1.17948477:64:86:01:ATTCCTCTTG` in the bam file. Thanks!
> 
> Best,
> Xin

As the GEO will convert the read name of fastq files, so it looks a bit different from the files generated by bcl2fastq. After converting, the cell_ID and UMI are the same as in the paper: ie. the 64:86:01 is the cell ID here (before merge sub-libraries) and the "ATTCCTCTTG" is UMI. And as you are already aware, the prefix for each sub-library used in the paper is listed in issue#2.

Best,
Chenxu

**Comment by xindongnov** [comment]
Hi @cxzhu,

Super! Thanks!

Best,
Xin
