### ISSUE TITLE
About the shellscript

### ISSUE THREAD

**Issue by YinCH97** [cxzhu/Paired-Tag#5]
Hello，
    When I run the shellscrips/01.pre_process_paired_tag_fastq.sh.I get this error:line 3: reachtools: command not found.What is the reason for this and how should I solve it？Thank you.

**Comment by cxzhu** [comment]
Hi @GLSBZych97, as in the instructions at the main page, you need to compile the reachtools and modify the path to the compiled file (and references) in the script.
