### ISSUE TITLE
How did you filter the pileup positions 

### ISSUE THREAD

**Issue by CharlieChang1996** [cxzhu/Paired-Tag#6]
Hi,
I am tring to reproduce the results of your paper and I noticed a step of filtering before downstream analysis:
_" Before generating the cell-counts matrices, DNA bam files were further filtered by removing high-pileup positions 
(cutoff=10) regardless of cellular barcode, PCR index and UMI"_
I can't find how you do it in the paper nor in this github repository. Can you give me some hints on what tools you used for this?

Thanks
Charlie

**Comment by cxzhu** [comment]
Hi @CharlieChang1996,

I have uploaded the scripts I used for this purpose from my collaborator @shawnzhangyx.

Please find them from: https://github.com/cxzhu/Paired-Tag/tree/master/remove_pileup
