### ISSUE TITLE
Separate DNA / RNA contamination reads from RNA / DNA libraries

### ISSUE THREAD

**Issue by Xieeeee** [cxzhu/Paired-Tag#8]
The DNA / RNA libraries construction using restriction enzymes to remove the other modality is very convenient, however in some libraries we can observe the "bleed through" of reads from the other modality, determined by the presence of RE cutting sites (GCGGCCGC or CCTGCAGG) at the end of R2. 

**It would be wonderful if reachtools can have a function to automatically determined whether a read is from DNA / RNA / undetermined** (considering the base accuracy maybe low at the very end) **from the sequenced libraries.**

🍺

**Comment by cxzhu** [comment]
assigned
